/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.rosmery.pe.presentacion;

/**
 *
 * @author Alumno-PB203
 */
public class JPPersonaDocumento extends javax.swing.JPanel {

    /**
     * Creates new form JPPersonaDocumento
     */
    public JPPersonaDocumento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textestado = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textpersona = new javax.swing.JLabel();
        txtnumerodocumento = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txttipodocumento = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        textnumerodocumento = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtpersona = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel1.setText("REgISTRO PERSONA DOCUMENTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        textestado.setForeground(new java.awt.Color(153, 153, 153));
        textestado.setText("ESTADO");
        jPanel1.add(textestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 20));

        txtestado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtestado.setBorder(null);
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 400, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 400, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setText("GUARDAR 2");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton2.setText("LIMPIAR 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        textpersona.setForeground(new java.awt.Color(153, 153, 153));
        textpersona.setText("PERSONA");
        jPanel1.add(textpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        txtnumerodocumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtnumerodocumento.setBorder(null);
        txtnumerodocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumerodocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtnumerodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 400, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 400, -1));

        txttipodocumento.setForeground(new java.awt.Color(153, 153, 153));
        txttipodocumento.setText("TIPO DOCUMENTO");
        jPanel1.add(txttipodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 400, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------", "MASCULINO", "FEMENINO " }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 400, -1));

        textnumerodocumento.setForeground(new java.awt.Color(153, 153, 153));
        textnumerodocumento.setText("NUMERO DOCUMENTO");
        jPanel1.add(textnumerodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 400, -1));

        txtpersona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpersona.setBorder(null);
        txtpersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonaActionPerformed(evt);
            }
        });
        jPanel1.add(txtpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtnumerodocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumerodocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumerodocumentoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Código para limpiar los campos de texto
    txtpersona.setText("");
    txttipodocumento.setText("");
    txtnumerodocumento.setText("");
    txtestado.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtpersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel textestado;
    private javax.swing.JLabel textnumerodocumento;
    private javax.swing.JLabel textpersona;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtnumerodocumento;
    private javax.swing.JTextField txtpersona;
    private javax.swing.JLabel txttipodocumento;
    // End of variables declaration//GEN-END:variables
}
